version: "3"
services: 
    
    nginx:
        container_name: middlenginx
        image: nginx:alpine
        #build: nginx
        #restart: always
        expose:
            - "80"
        ports: 
            - "80:80"
          #  - "433:433"
        #links:
        #    - api
        volumes:

            - ./nginx.middle.conf:/etc/nginx/conf.d/default.conf:rw
        #    - shared:/usr/share/nginx/html
        #    - ./nginx.conf:/etc/nginx/nginx.conf
            
        depends_on: 
            - api
        networks:
            - internalnet
    
    api:
        container_name: dotnetbackend
        build: 
            context: ./Assignment1
            dockerfile: ./Dockerfile
        ports: 
            - "5000:5000"
        restart: always
        depends_on: 
            - db
        #links:
        #    - db
        networks:
            - internalnet
            - backend 
        environment:
            DatabaseServer: localhost
            DatabaseName: SEP490_HFS_2
            DatabaseUser: sa
            DatabaseUserPassword: Passw0rd
    db:
        container_name: mssql
        hostname: mssql
        user: root
        build: 
            context: ./Db
            dockerfile: ./Dockerfile
        #network_mode: "host"
        ports: 
            - "1433:1433"
        restart: always
        environment:
            ACCEPT_EULA: Y
            MSSQL_SA_PASSWORD: Passw0rd

        volumes:
            - database-data:/var/opt/mssql
        networks:
            - backend   
volumes:
  database-data:
networks: 
    internalnet:
        driver: bridge
        ipam:
          config:
               - subnet: 172.9.9.0/24
    backend:
        external: true

